/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c ApcUpsMonAdaptor -a apcupscif eu.navlost.apcupsmon.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

// NOTE - I can't seem to get the relevant CMake macro to work in order to
// autogenerate the whole thing via qdbuscpp2xml and qdbusxml2cpp, so I just
// do it manually and include the generated files in the source distribution.
// FIXES are welcome.

#include "apcupscif.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ApcUpsMonAdaptor
 */

ApcUpsMonAdaptor::ApcUpsMonAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ApcUpsMonAdaptor::~ApcUpsMonAdaptor()
{
    // destructor
}

void ApcUpsMonAdaptor::connectToHost(const QString &host)
{
    // handle method call eu.navlost.apcupsmon.connectToHost
    QMetaObject::invokeMethod(parent(), "connectToHost", Q_ARG(QString, host));
}

void ApcUpsMonAdaptor::connectToHost(const QString &host, uint port)
{
    // handle method call eu.navlost.apcupsmon.connectToHost
    QMetaObject::invokeMethod(parent(), "connectToHost", Q_ARG(QString, host), Q_ARG(uint, port));
}

QString ApcUpsMonAdaptor::errorString()
{
    // handle method call eu.navlost.apcupsmon.errorString
    QString out0;
    QMetaObject::invokeMethod(parent(), "errorString", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString ApcUpsMonAdaptor::getUpsData(const QString &key)
{
    // handle method call eu.navlost.apcupsmon.getUpsData
    QString out0;
    QMetaObject::invokeMethod(parent(), "getUpsData", Q_RETURN_ARG(QString, out0), Q_ARG(QString, key));
    return out0;
}

QStringList ApcUpsMonAdaptor::getUpsKeys()
{
    // handle method call eu.navlost.apcupsmon.getUpsKeys
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "getUpsKeys", Q_RETURN_ARG(QStringList, out0));
    return out0;
}

void ApcUpsMonAdaptor::requestEvents()
{
    // handle method call eu.navlost.apcupsmon.requestEvents
    QMetaObject::invokeMethod(parent(), "requestEvents");
}

void ApcUpsMonAdaptor::requestStatus()
{
    // handle method call eu.navlost.apcupsmon.requestStatus
    QMetaObject::invokeMethod(parent(), "requestStatus");
}

void ApcUpsMonAdaptor::setInterval(int updateInterval)
{
    // handle method call eu.navlost.apcupsmon.setInterval
    QMetaObject::invokeMethod(parent(), "setInterval", Q_ARG(int, updateInterval));
}

void ApcUpsMonAdaptor::stopUpdates()
{
    // handle method call eu.navlost.apcupsmon.stopUpdates
    QMetaObject::invokeMethod(parent(), "stopUpdates");
}

